package vn.pmdata.test.model;

import oracle.jbo.server.ViewObjectImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 11 21:39:53 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FilmViewImpl extends  ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FilmViewImpl() {
    }
}

