package vn.pmdata.test.model;

 

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.domain.ClobDomain;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 11 21:39:53 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FilmViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_FILM = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        FilmId,
        Title,
        Description,
        ReleaseYear,
        LanguageId,
        OriginalLanguageId,
        RentalDuration,
        RentalRate,
        Length,
        ReplacementCost,
        Rating,
        SpecialFeatures,
        LastUpdate;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int FILMID = AttributesEnum.FilmId.index();
    public static final int TITLE = AttributesEnum.Title.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int RELEASEYEAR = AttributesEnum.ReleaseYear.index();
    public static final int LANGUAGEID = AttributesEnum.LanguageId.index();
    public static final int ORIGINALLANGUAGEID = AttributesEnum.OriginalLanguageId.index();
    public static final int RENTALDURATION = AttributesEnum.RentalDuration.index();
    public static final int RENTALRATE = AttributesEnum.RentalRate.index();
    public static final int LENGTH = AttributesEnum.Length.index();
    public static final int REPLACEMENTCOST = AttributesEnum.ReplacementCost.index();
    public static final int RATING = AttributesEnum.Rating.index();
    public static final int SPECIALFEATURES = AttributesEnum.SpecialFeatures.index();
    public static final int LASTUPDATE = AttributesEnum.LastUpdate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FilmViewRowImpl() {
    }
}

