package org.o7planning.adf.model.module;

import oracle.jbo.server.ApplicationModuleImpl;

import oracle.jbo.server.ViewObjectImpl;

import org.o7planning.adf.model.views.V00DepartmentsImpl;
import org.o7planning.adf.model.views.V00EmployeesImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 06 22:37:57 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for V00Departments1.
     * @return V00Departments1
     */
    public V00DepartmentsImpl getV00Departments1() {
        return (V00DepartmentsImpl) findViewObject("V00Departments1");
    }

    /**
     * Container's getter for V00Employees1.
     * @return V00Employees1
     */
    public V00EmployeesImpl getV00Employees1() {
        return (V00EmployeesImpl) findViewObject("V00Employees1");
    }

    /**
     * Container's getter for V01Employees1.
     * @return V01Employees1
     */
    public ViewObjectImpl getV01Employees1() {
        return (ViewObjectImpl) findViewObject("V01Employees1");
    }
}

