package org.o7planning.adf.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 07 16:18:04 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class V00DepartmentsImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public V00DepartmentsImpl() {
    }
}

